# Generated by Django 4.0.6 on 2022-07-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('kids', models.ManyToManyField(blank=True, to='hackernews.kid')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='kids',
            field=models.ManyToManyField(blank=True, to='hackernews.kid'),
        ),
    ]
