# Generated by Django 4.0.6 on 2022-07-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0003_remove_kid_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='kids',
        ),
    ]
