# Generated by Django 4.0.6 on 2022-07-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0004_remove_kid_kids'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopLoop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stopped', models.BooleanField(default=False)),
            ],
        ),
    ]
