# Generated by Django 4.0.6 on 2022-07-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0005_stoploop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='story',
            name='kids',
        ),
        migrations.DeleteModel(
            name='Kid',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
